### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [evarozman/APPR-2018-19#2]
Da boš lahko v četrtek predstavila svoj projekt, poskrbi, da se ti poročilo prevede. Iz njega odstrani del, ki je ostal iz vzorca (torej histogram, zemljevid, napredno analizo in Shiny) ter ga nadomesti s svojo vsebino.

Opažam še, da v `vizualizacija.r` kličeš program `uvozi.zemljevid.r` iz vzorčnega repozitorija:

https://github.com/evarozman/APPR-2018-19/blob/28f92cb25441a4352cb354d95d3bb7f2f3f595e7/vizualizacija/vizualizacija.r#L42

To bo sicer delovalo, a s tem izgubiš nadzor nad tem, kaj tvoj program počne - če bi tja postavil zlonamerno kodo, bi jo tvoj program izvedel. Namesto tega raje uporabi svoj program `uvozi.zemljevid.r` (ta se uvozi že iz `libraries.r`) - v izogib morebitnim težavam (na katere si morda že naletela) ga popravi v skladu z JernejcicZan/APPR-2018-19#1.

**Comment by evarozman** [comment]
Pozdravljeni,
v poročilu sem izbrisala vse vzorčne podatke, vizualizacijo pa še nameravam dodati. Navodil za uvoz zemljevida nisem povsem razumela, a sem popravila kodo tako, kot jo ima sošolec. Je sedaj vse pravilno?

**Comment by jaanos** [comment]
Mislil sem, da popraviš ustrezno vrstico v `lib/uvozi.zemljevid.r` (pri funkciji `readOGR` argument `pot` nadomestiš s `shp`) - ampak če ti uvažanje zemljevidov že deluje, ta sprememba ni potrebna (ne bo pa škodilo, če jo narediš).

Poročila ti zaenkrat ne prevede, saj kličeš program `analiza.r`, ki pa je še ostal od vzorca. Svetujem torej, da pobrišeš razdelek **Napredna analiza podatkov** (ali vsaj zakomentiraš ukaz `source` v njem). Glede na to, da (še) nimaš Shinyja, svetujem tudi, da pobrišeš vrstico `runtime: shiny` iz glave poročila - v RStudiu se bo tako namesto gumba *Run Document* pojavil gumb *Knit*, s katerim prevedeš poročilo v obliko HTML.

**Comment by evarozman** [comment]
Se opravičujem, zdaj sem pa razumela. Sem popravila oboje, poročilo mi odpre.

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij za zagovore. Če boš do predstavitve še kaj spreminjala, mi prosim javi, da jo posodobim.

Opozoril bi sicer na opis zadnje razpredelnice:

https://github.com/evarozman/APPR-2018-19/blob/10f221357014eb7e7238c06857a00b6137cf2261/projekt.Rmd#L56-L61

Sklepam, da gre za razpredelnico `razvitost`, tako da popravi zaporedno številko, ime in opis.

**Comment by evarozman** [comment]
Sem popravila, najlepša hvala!

**Comment by jaanos** [comment]
V redu, bom posodobil povezavo.
